### PR TITLE
DepthPickPass

### PR DESCRIPTION
**Pull request by unphased**
Thanks to @vanruesc for the assistance. This I think is not really clean enough to go in as-is, and files are not in their proper places. But I figured that I would include everything I did just to make it slightly easier to follow how everything works. 

DepthCopyMaterial.js, DepthSavePass.js, and depthreaddemo.js together form my first attempt, which is a depth reading pass. 

DepthPickMaterial, DepthPickPass, and DepthPickDemo are my 2nd iteration where I have improved on that first working prototype in the following:

- use a 2x2 rendertarget (1x1 did not work for me), making the pass much cheaper
- no extra texturepass stuff in the demo for viewing the depth read out
- a better API for triggering the pass to do its work on demand, shown in the demo
- much better separation of concerns.

Hopefully DepthPickMaterial and DepthPickPass are general and lightweight enough to be a solid way to extract a world space position out of the GPU depth buffer, allowing you to have as complex a scene as you want and perform a raycast in any direction you want. You will get a reasonably precise world space Vec3 position back in a callback. 

- I do wonder if i should allow passing a camera into the query rather than providing it with the constructor.

- There's a slight (always under 1% it seems) discrepancy between the computed GPU position and the raycasted value. I am trying a few things but I think that there are a few places where I might be doing something that is causing this discrepancy. It's already accurate "enough" for my purposes, but I really think that the GPU should be working with numbers and precision that can yield far greater than 1/1000 accuracy.

  Perhaps the RGBA unpacking formula is off. Or perhaps there is some 0.5 texel off-by-one error with texture coordinate computation from the mouse coordinates.

- any use of readPixels from webGL appear to cause chrome performance tab to show that frame or the next frame's GPU time as elapsing under that (or an adjacent checkRenderbufferStatus) call. So this inflates the profile's cpu time report and it seems like it may just be a bug there but I'm slightly worried about what other implications this may have.

### CODE REVIEW

**Comment by vanruesc** [comment]
Thanks for preparing this 👍 

From what I've gathered, this new pass samples depth and reconstructs the corresponding world space position. I think this is only half of what would be expected of a GPU raycasting implementation; we still need a way to actually pick/identify objects.

Three has an [example of GPU picking](https://threejs.org/examples/?q=ray#webgl_interactive_cubes_gpu) that assigns unique IDs (0-4999) as colors to objects and renders them into another render target for picking. This approach could be combined with the depth-based approach to get both the point of intersection as well as the ID of the object.

I plan on adding something like a G-buffer to `postprocessing` to unify common frame buffers such as color, depth, normals, luminance, etc. This system will also support additional buffers for custom data such as IDs. Let's keep this PR open until that's ready.

As a first step, I'll go ahead and add the `DepthSavePass` with an optional single-value-copy mode to `postprocessing`. My reasoning for this is that the `DepthSavePass` harmonizes with the existing `SavePass` and depth picking is a special use case.

**Comment by unphased** [comment]
I just pushed a change that implements cleanup of the event listeners i used to do mouse things. I havent been using classes in javascript for a while now so this was the only way I could come up with to ensure the same function object is being referenced to get them properly removed (they need (??) to be methods since they mutate the object state).

**Comment by unphased** [comment]
> a way to actually pick/identify objects

Yes, this isn't a complete gpu raycasting solution, and I didn't go for the second half (the object picked) because my application doesn't require it (regular CPU raycasting is fine since the things that i actually care about clicking on are not huge geometries). 

I think that there are two approaches to this feature... One is as you point out, in the context of a full deferred rendering pipeline, where you already have a g-buffer which can provide the depth information that I'm working with here. 

In my testing there is a wide range of slightly older hardware that truly epicly struggles with performance when we do any sort of postprocessing. For example on Firefox on Ubuntu 18.04 even with a GTX 1080Ti there is a huge amount of jank when the window is larger than 1500 or so pixels wide. When I test with my (just a few year old) macbook, most of the postprocessing demos are very sluggish also.

It is also unfortunate that three.js is not built to allow MRT which IIRC WebGL2 enables, I reckon that would allow us to much less expensively produce e.g. an object id buffer.

So, the other use case is to enable the postprocessing pipeline in a very lightweight way, almost even to the degree of using the postprocessing framework as a means to obtain this GPU raycasting. It is in this context that extracting a single texel based on the mouse position from scene depth out to a tiny renderbuffer (and similarly, rendering the scene to a very narrow id buffer based on the mouse position) could be potentially very valuable for improving performance for devices that don't perform well with the full screen postprocessing pipeline.

**Comment by vanruesc** [comment]
> For example on Firefox on Ubuntu 18.04 even with a GTX 1080Ti there is a huge amount of jank when the window is larger than 1500 or so pixels wide.

That sounds like a strange driver or browser issue to me.

> I reckon that would allow us to much less expensively produce e.g. an object id buffer

Yes, but MRT is only half of the story; we also need to be able to reliably modify built-in materials to render out custom data. Node materials might be the way to do that.

> When I test with my (just a few year old) macbook, most of the postprocessing demos are very sluggish also.

Macbooks without discrete GPUs may not be powerful enough to push the amount of pixels required for certain post processing setups. This depends on many factors but post processing has always been a heavyweight, resource-intensive task that requires much more VRAM and processing power compared to common rendering workloads, no matter the platform. WebGL is no exception.

It's worth noting that most of the demos render the Sponza model which has lots of triangles and uses alpha testing. This model is expensive to render and not really suited for mobile devices, even without post processing. However, the point of the demos is just to showcase all effects with all of their features. It doesn't matter if they run poorly on weak hardware as long as they don't crash. Optimizations for specific target devices are up to the end users of the library.

> My hope is that a barebones postprocessing render that doesn't hit shaders heavily shouldnt be significantly more costly than a regular forward rendering approach, and that doing a few shenanigans with tiny depth and index renderbuffers would have a negligible impact. I hope that's true, but it may not be true.

Rendering the full depth texture is basically free because it replaces the usual depth buffer. However, you can only render out data such as depth and IDs if you render to texture, unless you're willing to render your scene geometry twice. Consequently, it's always necessary to blit the rendered scene from the render target to screen later which requires bandwidth. However, GPU picking has a clear advantage in computational complexity over traditional raycasting so the gains outweigh the inherent cost of copying pixels.

**Comment by vanruesc** [comment]
I went ahead and added `DepthPickingPass` in `postprocessing@6.21.0`.

This PR wasn't quite clean enough for a merge, but it served as a useful reference implementation. Thanks for that!

The `DepthPickingPass` extends the `DepthSavePass` and offers a promise-based API for depth picking via `readDepth(ndc)`. The calculation of world positions is out of scope for this pass and should be performed by the user if needed. I've added an [example](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/DepthPickingPass.js~DepthPickingPass.html#instance-method-readDepth) for this use case to the documentation.

Depth picking is now used in the [ShockWaveDemo](https://vanruesc.github.io/postprocessing/public/demo/#shock-wave).

I'm closing this because ID-based object picking is a separate, isolated use case which can be revisited at a later time.

**Comment by unphased** [comment]
That’s awesome! Thank you.

By the way, I was also able improve performance about halfway to forward rendering in my app by adding a way to opt out of adding the NormalPass to EffectComposer in the @react-three/postprocessing implementation of this library. I expect that I’ll be able to get that upstreamed as well. And probably also the necessary plumbing for the promise.

Without the normal pass, on most devices I’m able to see equivalent or slightly higher performance in switching from regular rendering to rendering with my depth picking pass implementation with antialiasing turned off on the effectcomposer. So, the extra overhead of the render pass and depth picking pass is offset by not multisampling. This certainly is good enough for me!

**Comment by unphased** [comment]
I've reviewed the code on your `main` branch now and it looks like you've got both use cases implemented (full screen depth copy and read to cpu, and single texel depth copy and read to cpu), which is amazing. Thanks again. At first I was confused because you're always initializing the DepthSavePass's rendertarget to a 1x1 dimension but then i realized that there is probably a guarantee that setSize would run on initialization.

**Comment by vanruesc** [comment]
> there is probably a guarantee that setSize would run on initialization

Exactly, [setSize](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/Pass.js~Pass.html#instance-method-setSize) is one of the life-cycle methods that gets called when a pass is [initialized](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/Pass.js~Pass.html#instance-method-initialize) and every time [the size of the composer](https://vanruesc.github.io/postprocessing/public/docs/class/src/core/EffectComposer.js~EffectComposer.html#instance-method-setSize) is changed.

> it would be neat to use this depth picking technique for obtaining the scene depth of various materials that render with vertex shaders

I'm not sure I understand what you mean by that because all materials have a vertex shader. Do you mean materials that morph vertex positions inside the vertex shader? If so, then that's already supported since depth picking uses depth from a depth texture attachment.

**Comment by unphased** [comment]
>  If so, then that's already supported since depth picking uses depth from a depth texture attachment.
Yeah, thats what I mean though. It's a significant drawback of CPU raycasting in that there is simply no performant way to get a correct raycast of something that's been moved by a vertex shader.

**Comment by vanruesc** [comment]
Got it, thanks for clarifying!

**Comment by unphased** [comment]
@vanruesc I know this is random but I was tinkering with Vignette and I noticed dithering could help for it as well. It does not seem to be settable for vignette like it is for blur.

**Comment by vanruesc** [comment]
@unphased Right, Vignetting is a gradient effect which is susceptable to banding. Since it's an `Effect`, it gets wrapped in an `EffectPass` and supports dithering via [EffectPass.dithering](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/EffectPass.js~EffectPass.html#instance-get-dithering).

The `dithering` feature of the `BlurPass` is currently [deprecated](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/BlurPass.js~BlurPass.html#instance-member-dithering) and will probably be removed in the future because it requires multiple convolution shader programs which leads to awkward code. The `BlurPass` is mainly used to blur offscreen textures and it usually doesn't render to screen where dithering would be useful.

PS: Following [this comment](https://github.com/vanruesc/postprocessing/issues/263#issuecomment-774325540), I looked into dithering with float type buffers and found that it is only relevant for Uint8 buffers because high precision colors (12+ bits) don't exhibit banding. So dithering should be used with float type buffers.

**Comment by unphased** [comment]
I totally agree with everything there, cheers! 

Will take a look at toggling dithering on the effectpass! It's quite easy to see the banding with vignette. I wonder if dithering on the effectpass could serve the same purpose for when for some reason it is desired on the output from a blur pass?

**Comment by vanruesc** [comment]
> I wonder if dithering on the effectpass could serve the same purpose for when for some reason it is desired on the output from a blur pass?

It would be possible to use a `TextureEffect` in an `EffectPass` to render the result of the `BlurPass` to screen with dithering enabled. But this would, of course, require an additional fullscreen render operation.

I'm not sure yet if dithering should be removed from the `BlurPass`. The deprecation flag is just there to remind myself that _something_ needs to happen. Maybe there's a better way to implement optional dithering for this pass instead of axing it. We'll see.

**Pull request closed without merging**
