### PR TITLE
Provide es5 transpiled version with build

### PR DESCRIPTION
**Pull request by gunderson**
I was having trouble including this package while using browserify+aliasify plugin. Aliasify chokes on the provided, `build/postprocessing.js` file. Using this transpiled es5 script file instead, browserfy+aliasify was able to complete compiling 

Generated by
    $ babel --presets es2015 postprocessing.js > postprocessing.es5.js

### CODE REVIEW

**Comment by vanruesc** [comment]
Thanks for the PR!

> Aliasify chokes on the provided, build/postprocessing.js file.

That's interesting; could you specify what exactly fails? I tried out `aliasify` myself and made a small test package that looks like this:

```js
// src/index.js
var pp = require("foo");
var composer = new pp.EffectComposer();
```

```js
// Gruntfile.js
browserify: {
  options: {
    transform: [[
      "aliasify", {
        aliases: {
          "foo": "postprocessing"
        }
      }
    ]]
  },
  dist: {
    files: {
      "build/test.js": ["src/index.js"]
    }
  }
}
```

And it worked as expected. Although the bundle `build/postprocessing.js` still uses es2015 features, `aliasify` should be able to process it.

Adding a transpilation step to the build process is something I wanted to avoid, but seeing that other people are actually interested in this package is enough reason for me to add it after all.

However, instead of merging this PR, I think it's better if I just adjust the build setup to produce a transpiled bundle directly. This library will undergo more changes in the future and an automated transpilation step will probably be better in the long run. 

The failing CI check also reminded me that I should fix the dependencies :sweat_smile:

**Comment by vanruesc** [comment]
I've added babel to the build process in 7fb3a2f. 

This means that the bundle `build/postprocessing.js` is now a transpiled es5 script in the latest version 1.1.2. It would be nice if you could try it out and tell me if it solves your issue!

**Comment by gunderson** [comment]
Sure, here's the error I was getting. I haven't tried the new build, but I've just forked it with the intent of adding a branching feature. Thanks for adding the babel step :)

`$ browserify -t aliasify node_modules/postprocessing/build/postprocessing.js 
SyntaxError: Unexpected token (28:7) (while aliasify was processing /Users/pg/Development/repositories/TASK/node_modules/postprocessing/build/postprocessing.js) while parsing file: /Users/pg/Development/repositories/TASK/node_modules/postprocessing/build/postprocessing.js
    at Parser.pp.raise (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.semicolon (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:2243:59)
    at Parser.pp.parseExpressionStatement (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:2677:8)
    at Parser.pp.parseStatement (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:2462:160)
    at Parser.pp.parseBlock (/Users/pg/Development/repositories/TASK/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseFunctionBody (/Users/pg/Development/repositor`

**Comment by vanruesc** [comment]
It does indeed look like either browserify or aliasify just flopped as soon as one of them reached this line from the old build:

```js
  class AdaptiveLuminosityMaterial extends THREE.ShaderMaterial {
```

Makes me wonder why it worked for me when I tested it with good old grunt-browserify, but I guess all is well that ends well.

> I've just forked it with the intent of adding a branching feature to enable multiple render paths that can be recombined later. 

Sounds nice :)

**Pull request closed without merging**
