### PR TITLE
Add Outline Pass with associated demo

### LINKED ISSUE #64: Outline Pass
In the THREE.js examples there's an outline pass example that I want to use. Would you accept a PR with it (If I updated it toyour current code style, etc...)?

### PR DESCRIPTION
**Pull request by JakeDluhy**
OutlinePass is a big one! I implemented limited changes, except where I thought adding ES6 syntax would be appropriate. I tried to use the `CopyMaterial` directly but for whatever reason that wasn't working for me, so I instantiated it and then used its uniforms and shaders in a new Shader Material, like in the original example.

I tried to mimic code style as much as possible, but lmk if you'd like me to change anything.

I'm looking to use this in my project, so it would be awesome if we could get it merged and released as soon as is convenient for you!

Thanks!

Fixes #64

### CODE REVIEW

**Comment by JakeDluhy** [comment]
I added the FXAA Material for antialiasing. Turns out that the outline pass looks _really_ bad without antialiasing

**Comment by vanruesc** [comment]
Thanks a lot for this contribution!

I've looked at it and can confirm that it works. However, I won't be able to merge this as-is. Please bear with me as I try to explain my thoughts on this.

I must admit that I'm to blame for not clearly stating my expectations regarding code health. I'm seeing quite a lot of issues with the proposed code which I'll point out later.

> OutlinePass is a big one!

Indeed, it's very complex 😓  

> I tried to use the CopyMaterial directly but for whatever reason that wasn't working for me so I instantiated it and then used its uniforms and shaders in a new Shader Material, like in the original example.

😕 That's not good! Workarounds should always be the last resort and can rarely be justified.

#### Code Health

I don't know how familiar you are with the `three.js` code base, but it's an ever-changing environment. The `three.js` examples are not actively maintained because they are not part of the library's code base. The `three.js` maintainers focus on developing the main library and there's a good chance that the examples will not be updated properly every time there's an API change. As a result, a lot of the files in the `three.js` examples suffer from [software rot](https://en.wikipedia.org/wiki/Software_rot), but that's fine because they are just _examples_ after all.

With the `postprocessing` library I want to provide a package of well maintained and up-to-date filter effects. Copying the examples and changing them into a specific format is often not enough to achieve that. If you closely examine the passes in this library and compare them with the `three.js` examples, you'll notice many differences, especially in the shader code. The `OutlinePass` needs to be polished and optimised. Revising the `OutlinePass` is what kept me from integrating it into this library. It takes time to update it properly.

#### Review

- The `OutlinePass` could use the existing `BlurPass` instead of the old Gaussian blur similar to how the `BloomPass` does it. The edge detection shader could also be optimised or maybe even replaced with the SMAAColorEdgesMaterial.
- There's a lot of mixed indention in the proposed code. Tabs should be used. ESLint helps out with all syntax errors but not with all style errors. Newlines are another issue.
- Although this project doesn't use TypeScript, all variables should have explicit types. For example, the first parameter of the `OutlinePass` should be a `Vector2`. I could be wrong, but the parameter may not even be necessary.
- Materials should always follow the existing format even if they belong together. There should not be more than one class per file. Shaders must be organised in descriptive folders according to the existing style.
- `if(maskActive) { renderer.context.disable(renderer.context.STENCIL_TEST); }` should be replaced with `renderer.state.buffers.stencil.setTest(true|false)` calls. Finding these issues depends on how well you know the innards of `three.js`. Unfortunately, the [documentation](https://threejs.org/docs/#api/renderers/webgl/WebGLState) on this is non-existent. Check the [MaskPass](https://github.com/vanruesc/postprocessing/blob/master/src/passes/MaskPass.js) for reference.
- Furthermore, I'm very reluctant to include `FXAA`, `TAA`, `SSAA` and `MSAA` stuff since `SMAA` appears to be [superior in almost every aspect](http://international.download.nvidia.com/geforce-com/international/comparisons/watch-dogs/watch-dogs-anti-aliasing-comparison-1-smaa-vs-fxaa.html).
- The demo `App` shouldn't be modified. The `EffectComposer` already reports viewport size changes to all passes. The `FXAAMaterial` shouldn't be used like this to begin with because it defines resizing logic that requires a custom `FXAAPass` implementation. No shortcuts allowed.

I think there may be more issues, but I don't have enough time to look deeper.

#### What's Next

If you need the `OutlinePass` right now, then it might be best to just drop your ported code into your project and use it until the `OutlinePass` makes it into the `postprocessing` library, at which point you could simply remove the temporary code.

Despite all the criticism I must commend you for putting up with an unfamiliar coding style and still providing a working port of the `OutlinePass` 👍  

We could try and improve this PR to create a clean basis for the `OutlinePass`. It's very important to keep this PR simple, concise and focused. Right now, there's already too much noise going on. Of course, this depends on how much time you're willing to invest in this. 

I can also assure you that the `OutlinePass` will be included not later than March 2018.

**Comment by JakeDluhy** [comment]
Thanks for the feedback! As you can probably tell, I'm quite new to postprocessing, so something like SMAA vs FXAA is something that I wasn't even clocking. And you're right, in my frustration with getting it to work I pushed code that I am not proud off. Apolgies =).

Right now I'm a little pressed for time so I'll maintain a local copy that I will use for my own project. I'm hoping within the next few weeks I can go back and refactor this to work better. I'll fix everything here and try to implement anything else I can find, but this might require some more reviews on your part if you're ok with that.

p.s. ESlint actually can help out with styling issues as well. I'm a little ashamed that mixed case got in (I usually use spaces), but maybe think about adding https://eslint.org/docs/rules/indent#tab (or https://eslint.org/docs/rules/no-mixed-spaces-and-tabs) and https://eslint.org/docs/rules/padded-blocks (I wasn't quite sure what your newline style is)

**Comment by vanruesc** [comment]
> Apolgies =)

Hey, no problem. I know how bad deadlines can get. 

> I'm hoping within the next few weeks I can go back and refactor this

No need to rush, the work won't run away.

> this might require some more reviews on your part if you're ok with that.

Sure, I'll do what I can.

> ESlint actually can help out with styling issues as well

Thanks for the hint, I'll try that out 👌 

Good luck with your work!

**Comment by vanruesc** [comment]
Closing this since the `OutlinePass` is now part of the library.

**Pull request closed without merging**
